server:
  port: "8080"
  host: "localhost"
  mode: "debug"

database:
  host: "devdbsql.database.windows.net"
  port: "1433"
  user: "devsql"
  password: "${DB_PASSWORD}"
  database: "sqldev"

jwt:
  secret: "your-very-secure-secret-key-here"
  expiration: 24

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
