server:
  port: "8080"
  host: "localhost"
  mode: "debug"

database:
  host: "localhost"
  port: "1433"
  user: "sa"
  password: "dev_password"
  database: "go_crud_dev"

jwt:
  secret: "dev-secret-key-change-in-production"
  expiration: 24

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 1
