server:
  port: "8080"
  host: "localhost"
  mode: "debug"

database:
  host: "localhost"
  port: "1433"
  user: "sa"
  password: "your_password_here"
  database: "go_crud"

jwt:
  secret: "your-very-secure-secret-key-here"
  expiration: 24

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
